# Generated by Django 5.2.8 on 2025-12-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="Content of the doctor's note")),
                ('date', models.DateField(help_text='Date when the note was created')),
                ('medication', models.ForeignKey(help_text='Medication this note is associated with', on_delete=django.db.models.deletion.CASCADE, to='medtrackerapp.medication')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
